// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: api/removewatermark/removewatermark.proto

package removewatermark

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RemoveWatermarkSrvClient is the client API for RemoveWatermarkSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoveWatermarkSrvClient interface {
	// 去除版权处理
	RemoveWatermark(ctx context.Context, in *RemoveWatermarkReq, opts ...grpc.CallOption) (*RemoveWatermarkRes, error)
}

type removeWatermarkSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoveWatermarkSrvClient(cc grpc.ClientConnInterface) RemoveWatermarkSrvClient {
	return &removeWatermarkSrvClient{cc}
}

func (c *removeWatermarkSrvClient) RemoveWatermark(ctx context.Context, in *RemoveWatermarkReq, opts ...grpc.CallOption) (*RemoveWatermarkRes, error) {
	out := new(RemoveWatermarkRes)
	err := c.cc.Invoke(ctx, "/api.removewatermark.RemoveWatermarkSrv/RemoveWatermark", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoveWatermarkSrvServer is the server API for RemoveWatermarkSrv service.
// All implementations must embed UnimplementedRemoveWatermarkSrvServer
// for forward compatibility
type RemoveWatermarkSrvServer interface {
	// 去除版权处理
	RemoveWatermark(context.Context, *RemoveWatermarkReq) (*RemoveWatermarkRes, error)
	mustEmbedUnimplementedRemoveWatermarkSrvServer()
}

// UnimplementedRemoveWatermarkSrvServer must be embedded to have forward compatible implementations.
type UnimplementedRemoveWatermarkSrvServer struct {
}

func (UnimplementedRemoveWatermarkSrvServer) RemoveWatermark(context.Context, *RemoveWatermarkReq) (*RemoveWatermarkRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWatermark not implemented")
}
func (UnimplementedRemoveWatermarkSrvServer) mustEmbedUnimplementedRemoveWatermarkSrvServer() {}

// UnsafeRemoveWatermarkSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoveWatermarkSrvServer will
// result in compilation errors.
type UnsafeRemoveWatermarkSrvServer interface {
	mustEmbedUnimplementedRemoveWatermarkSrvServer()
}

func RegisterRemoveWatermarkSrvServer(s grpc.ServiceRegistrar, srv RemoveWatermarkSrvServer) {
	s.RegisterService(&RemoveWatermarkSrv_ServiceDesc, srv)
}

func _RemoveWatermarkSrv_RemoveWatermark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWatermarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoveWatermarkSrvServer).RemoveWatermark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.removewatermark.RemoveWatermarkSrv/RemoveWatermark",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoveWatermarkSrvServer).RemoveWatermark(ctx, req.(*RemoveWatermarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoveWatermarkSrv_ServiceDesc is the grpc.ServiceDesc for RemoveWatermarkSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoveWatermarkSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.removewatermark.RemoveWatermarkSrv",
	HandlerType: (*RemoveWatermarkSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemoveWatermark",
			Handler:    _RemoveWatermarkSrv_RemoveWatermark_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/removewatermark/removewatermark.proto",
}
