// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: api/removewatermark/removewatermark.proto

package removewatermark

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRemoveWatermarkSrvRemoveWatermark = "/api.removewatermark.RemoveWatermarkSrv/RemoveWatermark"

type RemoveWatermarkSrvHTTPServer interface {
	RemoveWatermark(context.Context, *RemoveWatermarkReq) (*RemoveWatermarkRes, error)
}

func RegisterRemoveWatermarkSrvHTTPServer(s *http.Server, srv RemoveWatermarkSrvHTTPServer) {
	r := s.Route("/")
	r.POST("/removewatermark/remove_watermark", _RemoveWatermarkSrv_RemoveWatermark0_HTTP_Handler(srv))
}

func _RemoveWatermarkSrv_RemoveWatermark0_HTTP_Handler(srv RemoveWatermarkSrvHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveWatermarkReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRemoveWatermarkSrvRemoveWatermark)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveWatermark(ctx, req.(*RemoveWatermarkReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveWatermarkRes)
		return ctx.Result(200, reply)
	}
}

type RemoveWatermarkSrvHTTPClient interface {
	RemoveWatermark(ctx context.Context, req *RemoveWatermarkReq, opts ...http.CallOption) (rsp *RemoveWatermarkRes, err error)
}

type RemoveWatermarkSrvHTTPClientImpl struct {
	cc *http.Client
}

func NewRemoveWatermarkSrvHTTPClient(client *http.Client) RemoveWatermarkSrvHTTPClient {
	return &RemoveWatermarkSrvHTTPClientImpl{client}
}

func (c *RemoveWatermarkSrvHTTPClientImpl) RemoveWatermark(ctx context.Context, in *RemoveWatermarkReq, opts ...http.CallOption) (*RemoveWatermarkRes, error) {
	var out RemoveWatermarkRes
	pattern := "/removewatermark/remove_watermark"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRemoveWatermarkSrvRemoveWatermark))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
