// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"remove-watermark/internal/biz"
	"remove-watermark/internal/conf"
	"remove-watermark/internal/data"
	"remove-watermark/internal/server"
	"remove-watermark/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	removeWatermarkRepo := data.NewRemoveWatermarkData(dataData, logger)
	removeWatermarkUsecase := biz.NewRemoveWatermarkUsecase(removeWatermarkRepo, logger, confData)
	removeWatermarkService := service.NewRemoveWatermarkService(removeWatermarkUsecase, logger, confData)
	grpcServer := server.NewGRPCServer(confServer, removeWatermarkService, logger)
	httpServer := server.NewHTTPServer(confServer, removeWatermarkService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
